# Generated by Django 6.0.1 on 2026-01-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchariapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='traveler_name',
            field=models.CharField(default='Traveler', max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=200),
        ),
    ]
