# Generated by Django 6.0.1 on 2026-01-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchariapp', '0003_alter_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
